<?php
/**
 * CYN Tourism - Language System (Consolidated)
 * Merged: language.php + en.php
 */

session_start();

// Default language
if (!isset($_SESSION['language'])) {
    $_SESSION['language'] = 'tr';
}

// Language strings
$lang = array();

// Turkish (default)
$lang['tr'] = array(
    'welcome' => 'Hos Geldiniz',
    'dashboard' => 'Dashboard',
    'transfers' => 'Transferler',
    'tours' => 'Turlar',
    'hotels' => 'Oteller',
    'invoices' => 'Faturalar',
    'vouchers' => 'Voucherler',
    'partners' => 'Partnerler',
    'drivers' => 'Soforler',
    'vehicles' => 'Araclar',
    'tour_guides' => 'Rehberler',
    'users' => 'Kullanicilar',
    'reports' => 'Raporlar',
    'settings' => 'Ayarlar',
    'logout' => 'Cikis',
    'login' => 'Giris',
    'email' => 'E-posta',
    'password' => 'Sifre',
    'remember_me' => 'Beni Hatirla',
    'forgot_password' => 'Sifremi Unuttum',
    'submit' => 'Gonder',
    'cancel' => 'Iptal',
    'save' => 'Kaydet',
    'delete' => 'Sil',
    'edit' => 'Duzenle',
    'view' => 'Goruntule',
    'search' => 'Ara',
    'filter' => 'Filtrele',
    'export' => 'Disa Aktar',
    'print' => 'Yazdir',
    'new_transfer' => 'Yeni Transfer',
    'new_tour' => 'Yeni Tur',
    'new_invoice' => 'Yeni Fatura',
    'company_name' => 'Sirket Adi',
    'contact_name' => 'Yetkili Adi',
    'phone' => 'Telefon',
    'address' => 'Adres',
    'pickup_location' => 'Alis Yeri',
    'dropoff_location' => 'Birakis Yeri',
    'pickup_date' => 'Alis Tarihi',
    'pickup_time' => 'Alis Saati',
    'return_date' => 'Donus Tarihi',
    'return_time' => 'Donus Saati',
    'flight_number' => 'Ucus Numarasi',
    'total_pax' => 'Toplam Kisi',
    'passenger_names' => 'Yolcu Isimleri',
    'vehicle_type' => 'Arac Tipi',
    'driver' => 'Sofor',
    'tour_guide' => 'Rehber',
    'hotel_name' => 'Otel Adi',
    'check_in' => 'Giris Tarihi',
    'check_out' => 'Cikis Tarihi',
    'nights' => 'Gece',
    'room_type' => 'Oda Tipi',
    'meal_plan' => 'Yemek Plani',
    'amount' => 'Tutar',
    'total_amount' => 'Toplam Tutar',
    'currency' => 'Para Birimi',
    'status' => 'Durum',
    'notes' => 'Notlar',
    'created_at' => 'Olusturma Tarihi',
    'updated_at' => 'Guncelleme Tarihi',
    'actions' => 'Islemler',
    'active' => 'Aktif',
    'inactive' => 'Pasif',
    'pending' => 'Beklemede',
    'confirmed' => 'Onaylandi',
    'completed' => 'Tamamlandi',
    'cancelled' => 'Iptal Edildi',
    'paid' => 'Odendi',
    'unpaid' => 'Odenmedi',
    'today_transfers' => 'Bugunku Transferler',
    'month_vouchers' => 'Bu Ay Voucher',
    'pending_invoices' => 'Bekleyen Faturalar',
    'month_revenue' => 'Aylik Gelir',
    'no_records' => 'Kayit bulunamadi',
    'success' => 'Basarili',
    'error' => 'Hata',
    'warning' => 'Uyari',
    'info' => 'Bilgi',
    'are_you_sure' => 'Emin misiniz?',
    'delete_confirm' => 'Bu kayidi silmek istediginize emin misiniz?',
    'save_success' => 'Kayit basariyla kaydedildi',
    'delete_success' => 'Kayit basariyla silindi',
    'update_success' => 'Kayit basariyla guncellendi',
    'required_field' => 'Bu alan zorunludur',
    'invalid_email' => 'Gecersiz e-posta adresi',
    'invalid_phone' => 'Gecersiz telefon numarasi',
    'select_option' => 'Seciniz',
    'all' => 'Tumu',
    'previous' => 'Onceki',
    'next' => 'Sonraki',
    'showing' => 'Gosteriliyor',
    'of' => '/',
    'entries' => 'kayit',
    'to' => '-',
    'from' => 'dan',
    'page' => 'Sayfa',
    'go' => 'Git',
    'reset' => 'Sifirla',
    'apply' => 'Uygula',
    'close' => 'Kapat',
    'back' => 'Geri',
    'home' => 'Anasayfa',
    'profile' => 'Profil',
    'change_password' => 'Sifre Degistir',
    'current_password' => 'Mevcut Sifre',
    'new_password' => 'Yeni Sifre',
    'confirm_password' => 'Sifre Tekrar',
    'password_mismatch' => 'Sifreler eslesmiyor',
    'password_changed' => 'Sifre basariyla degistirildi',
    'login_success' => 'Basariyla giris yaptiniz',
    'login_failed' => 'Giris basarisiz. Lutfen bilgilerinizi kontrol edin',
    'logout_success' => 'Basariyla cikis yaptiniz',
    'session_expired' => 'Oturumunuz sona erdi. Lutfen tekrar giris yapin',
    'access_denied' => 'Erisim reddedildi',
    'not_found' => 'Sayfa bulunamadi',
    'server_error' => 'Sunucu hatasi',
    'maintenance_mode' => 'Bakim modu aktif',
    'coming_soon' => 'Yakinda',
    'under_construction' => 'Yapim asamasinda',
    'copyright' => 'Tum haklari saklidir',
    'developed_by' => 'Gelistiren',
    'version' => 'Versiyon',
    'help' => 'Yardim',
    'support' => 'Destek',
    'contact' => 'Iletisim',
    'about' => 'Hakkimizda',
    'terms' => 'Kullanim Kosullari',
    'privacy' => 'Gizlilik Politikasi'
);

// English
$lang['en'] = array(
    'welcome' => 'Welcome',
    'dashboard' => 'Dashboard',
    'transfers' => 'Transfers',
    'tours' => 'Tours',
    'hotels' => 'Hotels',
    'invoices' => 'Invoices',
    'vouchers' => 'Vouchers',
    'partners' => 'Partners',
    'drivers' => 'Drivers',
    'vehicles' => 'Vehicles',
    'tour_guides' => 'Tour Guides',
    'users' => 'Users',
    'reports' => 'Reports',
    'settings' => 'Settings',
    'logout' => 'Logout',
    'login' => 'Login',
    'email' => 'Email',
    'password' => 'Password',
    'remember_me' => 'Remember Me',
    'forgot_password' => 'Forgot Password',
    'submit' => 'Submit',
    'cancel' => 'Cancel',
    'save' => 'Save',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'view' => 'View',
    'search' => 'Search',
    'filter' => 'Filter',
    'export' => 'Export',
    'print' => 'Print',
    'new_transfer' => 'New Transfer',
    'new_tour' => 'New Tour',
    'new_invoice' => 'New Invoice',
    'company_name' => 'Company Name',
    'contact_name' => 'Contact Name',
    'phone' => 'Phone',
    'address' => 'Address',
    'pickup_location' => 'Pickup Location',
    'dropoff_location' => 'Dropoff Location',
    'pickup_date' => 'Pickup Date',
    'pickup_time' => 'Pickup Time',
    'return_date' => 'Return Date',
    'return_time' => 'Return Time',
    'flight_number' => 'Flight Number',
    'total_pax' => 'Total Passengers',
    'passenger_names' => 'Passenger Names',
    'vehicle_type' => 'Vehicle Type',
    'driver' => 'Driver',
    'tour_guide' => 'Tour Guide',
    'hotel_name' => 'Hotel Name',
    'check_in' => 'Check In',
    'check_out' => 'Check Out',
    'nights' => 'Nights',
    'room_type' => 'Room Type',
    'meal_plan' => 'Meal Plan',
    'amount' => 'Amount',
    'total_amount' => 'Total Amount',
    'currency' => 'Currency',
    'status' => 'Status',
    'notes' => 'Notes',
    'created_at' => 'Created At',
    'updated_at' => 'Updated At',
    'actions' => 'Actions',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'pending' => 'Pending',
    'confirmed' => 'Confirmed',
    'completed' => 'Completed',
    'cancelled' => 'Cancelled',
    'paid' => 'Paid',
    'unpaid' => 'Unpaid',
    'today_transfers' => "Today's Transfers",
    'month_vouchers' => "This Month's Vouchers",
    'pending_invoices' => 'Pending Invoices',
    'month_revenue' => 'Monthly Revenue',
    'no_records' => 'No records found',
    'success' => 'Success',
    'error' => 'Error',
    'warning' => 'Warning',
    'info' => 'Info',
    'are_you_sure' => 'Are you sure?',
    'delete_confirm' => 'Are you sure you want to delete this record?',
    'save_success' => 'Record saved successfully',
    'delete_success' => 'Record deleted successfully',
    'update_success' => 'Record updated successfully',
    'required_field' => 'This field is required',
    'invalid_email' => 'Invalid email address',
    'invalid_phone' => 'Invalid phone number',
    'select_option' => 'Select',
    'all' => 'All',
    'previous' => 'Previous',
    'next' => 'Next',
    'showing' => 'Showing',
    'of' => 'of',
    'entries' => 'entries',
    'to' => 'to',
    'from' => 'from',
    'page' => 'Page',
    'go' => 'Go',
    'reset' => 'Reset',
    'apply' => 'Apply',
    'close' => 'Close',
    'back' => 'Back',
    'home' => 'Home',
    'profile' => 'Profile',
    'change_password' => 'Change Password',
    'current_password' => 'Current Password',
    'new_password' => 'New Password',
    'confirm_password' => 'Confirm Password',
    'password_mismatch' => 'Passwords do not match',
    'password_changed' => 'Password changed successfully',
    'login_success' => 'Login successful',
    'login_failed' => 'Login failed. Please check your credentials',
    'logout_success' => 'Logout successful',
    'session_expired' => 'Your session has expired. Please login again',
    'access_denied' => 'Access denied',
    'not_found' => 'Page not found',
    'server_error' => 'Server error',
    'maintenance_mode' => 'Maintenance mode is active',
    'coming_soon' => 'Coming soon',
    'under_construction' => 'Under construction',
    'copyright' => 'All rights reserved',
    'developed_by' => 'Developed by',
    'version' => 'Version',
    'help' => 'Help',
    'support' => 'Support',
    'contact' => 'Contact',
    'about' => 'About',
    'terms' => 'Terms of Use',
    'privacy' => 'Privacy Policy'
);

// Get current language
$currentLang = $_SESSION['language'] ?? 'tr';

// Translation function
function __($key) {
    global $lang, $currentLang;
    return $lang[$currentLang][$key] ?? $key;
}

// Set language function
function setLanguage($language) {
    global $currentLang;
    if (in_array($language, ['tr', 'en'])) {
        $_SESSION['language'] = $language;
        $currentLang = $language;
    }
}
